import { AuthBootstrap } from "@/context/providers/AuthBootstrap";
import { ReactQueryProvider } from "@/context/providers/react-query.provider";
import { ENV } from "@/types/env.type";
import { Construction } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="apple-mobile-web-app-title" content="Talent Insider" />
      </head>

      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          {process.env.NEXT_PUBLIC_ENV === ENV.CONSTRUCTION ? <Construction /> : <>
            <AuthBootstrap />
            {children}
            <Toaster />
          </>}
        </ReactQueryProvider>
      </body>
    </html >
  );
}
